config/routes.rb
Rails.application.routes.draw do

  root 'application#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, :addresses
  resources :products, :orders
  post "/checkout", to: "orders#checkout", as: :checkout

  #Rotas para as páginas de depositar e retirar dinheiro da conta
  resources :users do
    member do
      get :add_money
      get :retrieve_money
    end
  end
  get '/sign_up', to: 'users#new', as: :sign_up

  resources :sessions, only: [:new, :create, :destroy]
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :password, length: { minimum: 3 }, if: :new_user?
  validates :password, confirmation: true
  validates :email, uniqueness: true
  validates :name, :email, :cpf, :birth_date, :addresses, presence: true

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  accepts_nested_attributes_for :addresses

  #Método para adicionar ou retirar valor do saldo
  before_update :change_balance

  def change_balance
    if self.balance_changed?
      if !balance_was.nil?
        self.balance += self.balance_was
      end
    end
  end

  private
  def new_user?
    new_record?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end


  def show
  end

  def new
    @user = User.new
    @user.addresses.build
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        login(params[:user][:email], params[:user][:password])
        format.html { redirect_to root_path, notice: 'Usuario cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Cadastro alterado com sucesso.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Conta deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require('user').permit(:name, :email, :cpf, :birth_date, :password, :salt, :balance, addresses_attributes: [:id, :name, :cep, :street, :complement, :neighborhood, :city, :state])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= stylesheet_link_tag 'sign_in' %>
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "campos") %> incorretos:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <h3>Detalhes do cliente</h3>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="form-group col-md-8">
        <%= form.label :name, 'Nome Completo' %>
        <%= form.text_field :name, class: 'form-control', placeholder: "Seu nome aqui"%>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="form-group col-md-4">
        <%= form.label :email, 'Email' %>
        <%= form.email_field :email, class: 'form-control', placeholder: "example@email.com" %>
      </div>
      <div class="form-group col-md-4">
        <%= form.label :password, 'Senha' %>
        <%= form.password_field :password, class: 'form-control', placeholder: "Sua senha, deve ter 4 caracteres ou mais" %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="form-group col-md-4">
        <%= form.label :cpf, 'CPF' %>
        <%= form.text_field :cpf, class: 'form-control', placeholder: "000.000.000-00" %>
      </div>
      <div class="form-group col-md-4">
        <%= form.label :birth_date, 'Data de nascimento' %>
        <%= form.date_field :birth_date, class: 'form-control', placeholder: "DD/MM/YYYY" %>
      </div>
    </div>
    <%= form.fields_for :addresses do |form_address| %>
      <p></p>
      <div class="row justify-content-center">
        <div class="col-md-8">
          <h3>Detalhes do endereço</h3>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="form-group col-md-4">
          <%= form_address.label :name, 'Apelido do endereço' %>
          <%= form_address.text_field :name, class: 'form-control', placeholder: "Ex: Casa, Trabalho, Casa da minha vó" %>
        </div>
        <div class="form-group col-md-4">
          <%= form_address.label :cep, 'CEP' %>
          <%= form_address.text_field :cep, class: 'form-control', placeholder: "00000-000" %>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="form-group col-md-8">
          <%= form_address.label :street, 'Logradouro' %>
          <%= form_address.text_field :street, class: 'form-control', placeholder: "Seu endereço" %>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="form-group col-md-8">
          <%= form_address.label :complement, 'Complemento' %>
          <%= form_address.text_field :complement, class: 'form-control', placeholder: "Ex: Centro" %>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="form-group col-md-4">
          <%= form_address.label :neighborhood, 'Bairro' %>
          <%= form_address.text_field :neighborhood, class: 'form-control', placeholder: "Ex: Cruzeiro Velho" %>
        </div>
        <div class="form-group col-md-2">
          <%= form_address.label :city, 'Cidade' %>
          <%= form_address.text_field :city, class: 'form-control', placeholder: "Ex: Brasília" %>
        </div>
        <div class="form-group col-md-2">
          <%= form_address.label :state, 'Estado' %>
          <%= form_address.text_field :state, class: 'form-control', placeholder: "Ex: Distrito Federal" %>
        </div>
      </div>
    <% end %>

    <div class="row justify-content-center">
      <div id="button-padding" class="col-md-8">
        <% if @user.created_at == nil %>
        <%= form.submit :Cadastrar, class: 'btn btn-success' %>
        <% else %>
          <%= form.submit :Editar, class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/users/add_money.html.erb
<% if current_user.nil? %>
  <h4><strong>Oops!</strong></h4>
  <h4>Parece que você não está logado, logue para acessar essa página.</h4>
  <%= link_to 'Logar', log_in_path %>
<% else %>
  <h4>
    <% if current_user.balance.nil?%>
      <% current_user.balance = 0 %>
    <% end %>
    Saldo Atual: R$<%= '%.2f' % current_user.balance %>
  </h4>

  <%= form_with model: current_user do |form| %>
    <div class="field">
      <%= form.label :balance, 'Valor a depositar:'%>
      <%= form.number_field :balance, step: :any, min: '0', value: '0' %>
    </div>

    <div class="field">
      <%= form.label :password, 'Confirme a senha para concluir o depósito: ' %>
      <%= form.password_field :password%>
    </div>

    <div class="actions">
      <%= form.submit "Concluir depósito" %>
    </div>
  <% end %>


<% end %>

app/views/users/edit.html.erb
<% if logged_in? %>
  <% if current_user.id == @user.id %>

    <h1>Editing User</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Voltar', @user %>

  <% else %>
    <h4 style="color: red">Erro: Acesso Negado!</h4>
  <% end %>
<% else %>
  <h4 style="color: red">Oops...Parece que você não está logado</h4>
  <%= link_to 'Logar', log_in_path %>
<% end %>

<%= link_to 'Voltar', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<% if logged_in? %>
<h1>Bem Vindo <%= current_user.name %> <%= link_to 'Log Out', log_out_path, method: :delete %></h1>

  <% if current_user.adm != true %>
    <h1>Seu Usuário</h1>

  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Criado em:</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
        <tr>
          <td><%= current_user.name %></td>
          <td><%= current_user.email %></td>
          <td><%= current_user.created_at %></td>
          <td><%= link_to 'Show', current_user %></td>
          <td><%= link_to 'Edit', edit_user_path(current_user) %></td>
          <td><%= link_to 'Destroy', current_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    </tbody>
  </table>

  <% else %>
    <h1>Lista de Usuários</h1>

    <table>
      <thead>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Criado em:</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.created_at %></td>
          <td><%= link_to 'Show', user %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

  <% end %>

<%else %>
  <h4>É preciso logar para ver essa página</h4>
  <%= link_to 'New User', new_user_path %>
  <%= link_to 'Log In', log_in_path %>
<% end %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/retrieve_money.html.erb
<% if current_user.nil? %>
  <h4><strong>Oops!</strong></h4>
  <h4>Parece que você não está logado, logue para acessar essa página.</h4>
  <%= link_to 'Logar', log_in_path %>
<% else %>
  <h4>
    <% if current_user.balance.nil?%>
      <% current_user.balance = 0 %>
    <% end %>
    Saldo Atual: R$<%= '%.2f' % current_user.balance %>
  </h4>

  <%= form_with model: current_user do |form| %>
    <div class="field">
      <%= form.label :balance, 'Valor a retirar:'%>
      R$<%= '%.2f' % current_user.balance %>
      <%= form.number_field :balance, step: :any, max: '0', min: -current_user.balance, value: '0' %>
    </div>

    <div class="field">
      <%= form.label :password, 'Confirme a senha para concluir a retirada de crédito' %>
      <%= form.password_field :password%>
    </div>

    <div class="actions">
      <%= form.submit "Retirar Dinheiro" %>
    </div>
  <% end %>


<% end %>

app/views/users/show.html.erb
<% if logged_in? %>
  <% if current_user.adm == true or current_user.id == @user.id %>
    <% javascript_include_tag "profile" %>
    <p id="notice"><%= notice %></p>
    <div class="card border-success">
      <div class="card-header">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item" role="presentation">
            <a class="nav-link active" id="home-tab" data-toggle="tab" onclick="show_button('profile', 'history')" href="#profile" role="tab" aria-controls="home" aria-selected="true" style="color: #194b03">Perfil</a>
          </li>
          <li class="nav-item" role="presentation">
            <a class="nav-link" id="contact-tab" data-toggle="tab" onclick="show_button('history', 'profile')" href="#history" role="tab" aria-controls="contact" aria-selected="false" style="color: #194b03">Historico
              de compras</a>
          </li>
        </ul>
      </div>
      <div class="card-body">
        <div class="container-fluid">
          <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="profile" role="tabpanel" aria-labelledby="home-tab">
              <div class="row justify-content-start">
                <div class="col-md-4">
                  <h3>Dados pessoais</h3>
                  <p>
                    <strong>Nome:</strong>
                    <%= @user.name %>
                  </p>
                  <p>
                    <strong>CPF:</strong>
                    <%= @user.cpf %>
                  </p>
                  <p>
                    <strong>Email:</strong>
                    <%= @user.email %>
                  </p>
                  <p>
                    <strong>Data de nascimento:</strong>
                    <%= @user.birth_date %>
                  </p>
                  <% if current_user.id == @user.id %>
                    <p>
                      <strong>Saldo:</strong>
                      <% if @user.balance.nil?%>
                        <% @user.balance = 0 %>
                      <% end %>
                      R$<%= '%.2f' % @user.balance %>
                    </p>
                    <%= link_to 'Depositar dinheiro', add_money_user_path(@user)%>
                    <%= link_to 'Recuperar dinheiro', retrieve_money_user_path(@user)%>
                  <br>
                  <%= link_to 'Editar dados pessoais', edit_user_path(@user) %>
                  <p>
                    <%= link_to 'Adicionar endereço', new_address_path, user: @user%>
                  <% end %>
                </div>
                <% count = 1 %>
                <% @user.addresses.each do |address| %>
                  <div class="col-md-4">
                    <h4>Endereço <%= count %></h4>
                    <% count += 1 %>
                    <p>
                      <strong>Nome:</strong>
                      <%= address.name %>
                    </p>
                    <p>
                      <strong>CEP:</strong>
                      <%= address.cep %>
                    </p>
                    <p>
                      <strong>Logradouro:</strong>
                      <%= address.street %>
                    </p>

                    <p>
                      <strong>Complemento:</strong>
                      <%= address.complement %>
                    </p>
                    <p>
                      <strong>Bairro:</strong>
                      <%= address.neighborhood %>
                    </p>
                    <p>
                      <strong>Cidade:</strong>
                      <%= address.city %>
                    </p>
                    <p>
                      <strong>Estado:</strong>
                      <%= address.state %>
                    </p>
                    <small><%= link_to 'Excluir', address_path(address), method: :delete, data: { confirm: 'Excluir?' } %></small>
                    <br>
                  </div>
                <% end %>
                <div class="tab-pane fade" id="history" role="tabpanel" aria-labelledby="contact-tab">

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  <% else %>
    <h4 style="color: red">Erro: Acesso Negado!</h4>
  <% end %>
<% else %>
  <h4 style="color: red">Oops...Parece que você não está logado</h4>
  <%= link_to 'Logar', log_in_path %>
<% end %>

<%= link_to 'Voltar', users_path %>