config/routes.rb
Rails.application.routes.draw do

  root 'application#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, :addresses
  resources :products, :orders
  post "/checkout", to: "orders#checkout", as: :checkout

  #Rotas para as páginas de depositar e retirar dinheiro da conta
  resources :users do
    member do
      get :add_money
      get :retrieve_money
    end
  end
  get '/sign_up', to: 'users#new', as: :sign_up

  resources :sessions, only: [:new, :create, :destroy]
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :products
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    skip_before_action :verify_authenticity_token, only: :checkout

    def index
        @orders = Order.all
        @products = Product.all
        @users = User.all
    end
  
    def create
        order = Order.new(orders_params)
        begin
            order.save!
            flash[:notice] = "Pedido de #{order.product.name} adicionado com sucesso!"
        rescue => exc
            puts exc
            flash[:notice] = exc
        ensure
            redirect_to orders_path
        end
    end
  
    def new
        @order = Order.new
        @product = Product.find_by(params[:id])
    end
  
    def edit
        @order = Order.find(params[:id])
        @product = Product.find(@order.product_id)
    end
  
    def show
        @order = Order.find(params[:id])
        @product = Product.find(@order.product_id)
        @total_value = @order.quantity * @product.price
    end
  
    def update
        order = Order.find(params[:id])
        begin
            order.update!(orders_params)
            flash[:notice] = "Pedido alterado com sucesso!"
        rescue => exc
            puts exc
            flash[:notice] = exc
        ensure
            redirect_to orders_path
        end
    end
  
    def destroy
        order = Order.find(params[:id])
        begin
            order.destroy!
            flash[:notice] = "Pedido de #{order.product.name} deletado com sucesso!"
        rescue => exc
            puts exc
            flash[:notice] = exc
        ensure
            redirect_to orders_path
        end
    end

    def checkout

        puts params
        final = 0.0
        params["_json"].each do |item|
            Order.create(user_id: current_user.id, product_id: item[:id], quantity: item[:count])
            price = item[:price]
            qnt = item[:count]
            final = price * qnt
        end
        current_user.balance = -final
        current_user.save!
        # Order.all.each do |order|
        #     if order.user_id === current_user.id
        #         begin
        #             product = Product.find(order.product_id)
        #             if product.quantity >= order.quantity
        #                 product.quantity -= order.quantity
        #                 product.save!
        #                 order.destroy!
        #                 flash[:notice] = "Compra finalizada com sucesso"
        #             else
        #                 order.destroy!
        #                 flash[:notice] = "Oops! Parece que a quantidade selecionada do produto #{product.name} não está mais disponível. Removendo do carrinho..."
        #                 break
        #             end
        #         rescue => exc
        #             puts exc
        #             flash[:notice] = exc
        #         ensure
        #             redirect_to orders_path
        #         end
        #     end
        # end
    end
    helper_method :checkout

    private

    def orders_params
        params.require('order').permit(:quantity, :product_id, :user_id)
    end


 end
 

app/helpers/orders_helper.rb
module OrdersHelper
  def final_price
    orders = Order.all
    price = 0.0
    orders.each do |order|
      if current_user.id === order.user_id
        product = Product.find(order.product_id)
        price += order.quantity * product.price
      end
    end
    return price
  end

end

app/views/orders/edit.html.erb
<% if current_user.nil? %>
  <h4 style="color: red">Oops...Parece que você não está logado</h4>
  <%= link_to 'Logar', log_in_path %>

<% elsif current_user.id != @order.user_id%>
  <h4 style="color: red">Oops...Parece que esse produto não pertence a sua Conta</h4>
  <%= link_to 'Meu Carrinho', orders_path %>

<% else %>

  <h1>Editar pedido</h1>
  <h3>Produto: <%= @product.name %></h3>
  <%= form_with model: @order do |form| %>
    <div class="field">
      <%= form.label :quantity, 'Quantidade' %>
      <%= form.select :quantity, options_for_select(1..@product.quantity) %>
    </div>

    <div class="actions">
      <%= form.submit "Atualizar pedido" %>
    </div>
  <% end %>

  <%= link_to 'Voltar', orders_path %>
<% end %>

app/views/orders/index.html.erb
<% if current_user %>
  <h1>Carrinho</h1>
  <table>
    <thead>
    <tr>
      <th>Produto</th>
      <th>Quantidade</th>
      <th>Preço total</th>
    </tr>
    </thead>
    <tbody>

      <% @orders.each do |order| %>
        <% if current_user.id == order.user_id %>
          <tr>
            <td><%= @products.find(order.product_id).name %></td>
            <td><%= order.quantity %></td>
            <td>R$<%= '%.2f' % (@products.find(order.product_id).price * order.quantity) %></td>
            <td><%= link_to 'Editar pedido', edit_order_path(order) %></td>
            <td><%= link_to 'Detalhes do pedido', order_path(order) %></td>
            <td><%= link_to 'Excluir pedido', order_path(order), method: :delete, data: { confirm: 'Excluir?' } %></td>
          </tr>
        <% end %>
      <% end %>

    </tbody>
  </table>

  <% if current_user.balance.nil? %>
    <% current_user.balance = 0.0 %>
  <% end %>
  <p>
    <strong>Seu saldo: R$<%= '%.2f' % current_user.balance %></strong>
  </p>

  <p>
    <strong>Valor final: R$<%= '%.2f' % final_price %></strong>

    <%= link_to 'Finalizar Compra', checkout_path, method: :post%>
  </p>
  <p><%= link_to 'Continuar Comprando', products_path %></p>

  <% else %>
    <h5>Logue em sua conta para acessar seu carrinho</h5>
    <%= link_to 'Logar', log_in_path %>
  <% end %>

app/views/orders/new.html.erb
<h6>Oops...Parece que a página que você está tentando acessar se encontra indisponível, caso deseje comprar algum produto acesse nossa página de produtos:</h6>
<%= link_to "Nossos Produtos", products_path%>
<!--
 <h1>Novo pedido</h1>

<%= form_with model: @order do |form| %>
  <div class="field">
    <%= form.label :quantity, 'Quantidade:' %>
    <%= form.number_field :quantity %>
    </div>

   <div class="field">
     <%= form.label :product_id, 'Produto'%>
     <%= form.select :product_id, options_for_select(Product.all.map { |product| [product.name, product.id] }) %>
   </div>

   <div class="field">
     <%= form.label :user_id, 'Usuário:'%>
     <%= form.select :user_id, options_for_select(User.all.map { |user| [user.name, user.id] }) %>
   </div>

    #descobrir como colocar o maximo dos produtos disponiveis


  <div class="actions">
  <%= form.submit "Finalizar pedido" %>
</div>
<% end %>

 <%= link_to 'Voltar', orders_path %>
!-->

app/views/orders/show.html.erb
<% if current_user.nil? %>
  <h4 style="color: red">Oops...Parece que você não está logado</h4>
  <%= link_to 'Logar', log_in_path %>

  <% elsif current_user.id != @order.user_id%>
  <h4 style="color: red">Oops...Parece que esse produto não pertence a sua Conta</h4>
  <%= link_to 'Meu Carrinho', orders_path %>

  <% else %>
<h1>Detalhes do pedido</h1>

    <p>
      <strong>Produto:</strong>
      <%= @product.name %>
    </p>
    
    <p>
      <strong>Quantidade:</strong>
      <%= @order.quantity %>
    </p>

    <p>
      <strong>Preço Total:</strong>
      R$<%= '%.2f' % @total_value %>
    </p>

    <p>
      <strong>Preço Individual:</strong>
      R$<%= '%.2f' % @product.price %>
    </p>

    <p>
      <strong>Adicionado em:</strong>
      <%= @order.created_at %>
    </p>

    <p>
      <strong>Editado em:</strong>
      <%= @order.updated_at %>
    </p>

    <%= link_to 'Editar', edit_order_path(@order) %>
    <%= link_to 'Voltar', orders_path %>

<% end %>