config/routes.rb
Rails.application.routes.draw do

  root 'application#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, :addresses
  resources :products, :orders
  post "/checkout", to: "orders#checkout", as: :checkout

  #Rotas para as páginas de depositar e retirar dinheiro da conta
  resources :users do
    member do
      get :add_money
      get :retrieve_money
    end
  end
  get '/sign_up', to: 'users#new', as: :sign_up

  resources :sessions, only: [:new, :create, :destroy]
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    @address = Address.all
    @user = User.all
  end

  def create
    @address = Address.new(address_params)
    begin
      @address.user_id = current_user.id
      @address.save!
      flash[:notice] = "#{@address.name} adicionado com sucesso!"
    rescue => exc
      puts exc
      flash[:notice] = exc
    ensure
      redirect_to user_path(current_user.id)
    end
  end

  def new
    @address = Address.new
  end

  def edit
    @address = Address.find(params[:id])
    @user = User.all
  end

  def show
    @address = Address.find(params[:id])
    @user = User.all
  end

  def _show
    @address = Address.find(params[:id])
    @user = User.all
  end

  def update
    address = Address.find(params[:id])
    begin
      address.update!(address_params)
      flash[:notice] = "Endereço modificado com sucesso!"
    rescue => exc
      puts exc
      flash[:notice] = exc
    ensure
      redirect_to address_path
    end
  end

  def destroy
    address = Address.find(params[:id])
    begin
      address.destroy!
      flash[:notice] = "#{address.name} deletado com sucesso!"
    rescue => exc
      puts exc
      flash[:notice] = exc
    ensure
      redirect_to user_path(current_user.id)
    end
  end

  private

  def address_params
    params.require('address').permit(:user_id, :cep, :name, :street, :complement, :neighborhood, :city, :state)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/edit.html.erb
<% if logged_in? %>
  <% if current_user.id == @address.user_id %>
    <h1>Editar endereço</h1>

    <%= form_with model: @addresses do |form_address| %>
      <p></p>
      <div class="row justify-content-center">
        <div class="col-md-8">
          <h3>Detalhes do endereço</h3>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="form-group col-md-4">
          <%= form_address.label :name, 'Apelido do endereço' %>
          <%= form_address.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group col-md-4">
          <%= form_address.label :cep, 'CEP' %>
          <%= form_address.text_field :cep, class: 'form-control' %>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="form-group col-md-8">
          <%= form_address.label :street, 'Logradouro' %>
          <%= form_address.text_field :street, class: 'form-control' %>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="form-group col-md-8">
          <%= form_address.label :complement, 'Complemento' %>
          <%= form_address.text_field :complement, class: 'form-control' %>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="form-group col-md-4">
          <%= form_address.label :neighborhood, 'Bairro' %>
          <%= form_address.text_field :neighborhood, class: 'form-control' %>
        </div>
        <div class="form-group col-md-2">
          <%= form_address.label :city, 'Cidade' %>
          <%= form_address.text_field :city, class: 'form-control' %>
        </div>
        <div class="form-group col-md-2">
          <%= form_address.label :state, 'Estado' %>
          <%= form_address.text_field :state, class: 'form-control' %>
        </div>
      </div>
      <div class="row justify-content-center">
        <div id="button-padding" class="col-md-8">
          <%= form_address.submit :Cadastrar, class: 'btn btn-success' %>
        </div>
      </div>
    <% end %>
  <% else %>
    <h4 style="color: red">Erro: Acesso Negado</h4>
    <%= link_to 'Voltar', addresses_path %>
  <% end %>
<% else %>
  <h4 style="color: red">Oops...Parece que você não está logado</h4>
  <%= link_to 'Logar', log_in_path %>
<% end %>

app/views/addresses/index.html.erb
<% if logged_in? %>

    <h1>Endereços</h1>

    <table>
      <thead>
      <tr>
        <th>usuario</th>
        <th>CEP</th>
        <th>Logradouro</th>
        <th>Complemento</th>
        <th>bairro</th>
        <th>localidade</th>
        <th>cidade</th>
        <th>estado</th>
      </tr>
      </thead>

      <tbody>
      <% @address.each do |address| %>
        <tr>
          <% if current_user.adm == true or current_user.id == address.user_id %>
            <td><%= address.user.name %></td>
            <td><%= address.cep %></td>
            <td><%= address.name %></td>
            <td><%= address.street %></td>
            <td><%= address.complement %></td>
            <td><%= address.neighborhood %></td>
            <td><%= address.city %></td>
            <td><%= address.state %></td>
            <td><%= link_to 'Detalhes do endereço', address_path(address) %></td>
            <% if current_user.id == address.user_id %>
              <td><%= link_to 'Editar endereço', edit_address_path(address) %></td>
              <td><%= link_to 'Excluir endereço', address_path(address), method: :delete, data: { confirm: 'Excluir?' } %></td>
            <%end %>
          <% end %>
        </tr>
      <% end %>
  </tbody>
  <td><%= link_to 'Novo endereço', new_address_path %></td>
</table>
<% else %>
<h4 style="color: red">Oops...Parece que você não está logado</h4>
<%= link_to 'Logar', log_in_path %>
<% end %>

app/views/addresses/new.html.erb
<h1>Novo endereco</h1>
<%= form_with model: @address do |form_address| %>
  <p></p>
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h3>Detalhes do endereço</h3>
    </div>
  </div>
  <div class="row justify-content-center">

    <div class="form-group col-md-4">
      <%= form_address.label :name, 'Apelido do endereço' %>
      <%= form_address.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group col-md-4">
      <%= form_address.label :cep, 'CEP' %>
      <%= form_address.text_field :cep, class: 'form-control' %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="form-group col-md-8">
      <%= form_address.label :street, 'Logradouro' %>
      <%= form_address.text_field :street, class: 'form-control' %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="form-group col-md-8">
      <%= form_address.label :complement, 'Complemento' %>
      <%= form_address.text_field :complement, class: 'form-control' %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="form-group col-md-4">
      <%= form_address.label :neighborhood, 'Bairro' %>
      <%= form_address.text_field :neighborhood, class: 'form-control' %>
    </div>
    <div class="form-group col-md-2">
      <%= form_address.label :city, 'Cidade' %>
      <%= form_address.text_field :city, class: 'form-control' %>
    </div>
    <div class="form-group col-md-2">
      <%= form_address.label :state, 'Estado' %>
      <%= form_address.text_field :state, class: 'form-control' %>
      <input id="user_id" name="user_id" type="hidden" value="<%= current_user.id %>" />
    </div>
  </div>
  <div class="row justify-content-center">
    <div id="button-padding" class="col-md-8">
      <%= form_address.submit :Cadastrar, class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

 <%= link_to 'Voltar', addresses_path %>

app/views/addresses/show.html.erb
<% if logged_in? %>
  <% if current_user.id == @address.user_id or current_user.adm == true %>
    <h1>Detalhes do endereco</h1>

    <p>
      <strong>Usuário:</strong>
      <%= @address.user.name %>
    </p>

    <p>
      <strong>Apelido:</strong>
      <%= @address.name %>
    </p>

    <p>
      <strong>CEP:</strong>
      <%= @address.cep %>
    </p>

    <p>
      <strong>Rua:</strong>
      <%= @address.street %>
    </p>

    <p>
      <strong>Complemento:</strong>
      <%= @address.complement %>
    </p>

    <p>
      <strong>Bairro:</strong>
      <%= @address.neighborhood %>
    </p>

    <p>
      <strong>Cidade:</strong>
      <%= @address.city %>
    </p>

    <p>
      <strong>Estado:</strong>
      <%= @address.state %>
    </p>

    <p>
      <strong>Adicionado em:</strong>
      <%= @address.created_at  %>
    </p>

    <% if current_user.id == @address.user_id %>
        <%= link_to 'Editar', edit_address_path(@address) %> |
    <% end %>
        <%= link_to 'Voltar', addresses_path %>
    <% else %>
        <h4 style="color: red">Erro: Acesso Negado</h4>
        <%= link_to 'Voltar', addresses_path %>
    <% end %>
<% else %>
  <h4 style="color: red">Oops...Parece que você não está logado</h4>
  <%= link_to 'Logar', log_in_path %>
<% end %>