config/routes.rb
Rails.application.routes.draw do

  root 'application#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, :addresses
  resources :products, :orders
  post "/checkout", to: "orders#checkout", as: :checkout

  #Rotas para as páginas de depositar e retirar dinheiro da conta
  resources :users do
    member do
      get :add_money
      get :retrieve_money
    end
  end
  get '/sign_up', to: 'users#new', as: :sign_up

  resources :sessions, only: [:new, :create, :destroy]
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def create
    product = Product.new(products_params)
    begin
      product.save!
      flash[:notice] = "Produto #{product.name} adicionado com sucesso!"
      redirect_to products_path
    rescue => exc
      puts exc
      flash[:notice] = exc
      redirect_to new_product_path
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
    @order = Order.new
  end

  def update
    product = Product.find(params[:id])
    begin
      product.update!(products_params)
      flash[:notice] = "Produto #{product.name} alterado com sucesso!"
      redirect_to products_path
    rescue => exc
      puts exc
      flash[:notice] = exc
      redirect_to edit_product_path
    end
  end

  def destroy
    product = Product.find(params[:id])
    begin
      product.destroy!
      flash[:notice] = "Produto #{product.name} deletado com sucesso!"
    rescue => exc
      puts exc
      flash[:notice] = exc
    ensure
      redirect_to products_path
    end
  end

  private

  def products_params
    params.require('product').permit(:name, :alcoholic, :category_id, :quantity, :price, :volume, :brand)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
  def in_cart?(product)
    orders = Order.all
    orders.each do |order|
      if current_user.id === order.user_id
        if order.product_id === product.id
          return true
        end
      end
    end
    return false
  end
end

app/views/products/edit.html.erb
<% if current_user.nil? %>
  <h4 style="color: red">Erro: é preciso estar logado em uma conta com função de administrador para acessar essa página!</h4>

<% elsif current_user.adm != true %>
  <h4 style="color: red">Erro: é preciso ter permissão de administrador para acessar essa página!</h4>
<% else %>
  <h1>Editar Produto</h1>

  <%= form_with model: @product do |form| %>
    <div class="field">
      <%= form.label :name, 'Nome' %>
      <%= form.text_field :name, value: @product.name %>
    </div>

    <div class="field">
      <%= form.label :brand, 'Marca' %>
      <%= form.text_field :brand, value: @product.brand %>
    </div>


    <div class="field">
      <%= form.label :volume, 'Volume' %>
      <%= form.text_field :volume, value: @product.volume %>
    </div>

    <div class="field">
      <%= form.label :alcoholic, 'Alcoólico?' %>
      <%= form.select :alcoholic, [['Sim', true], ['Não', false]] %>
    </div>

    <div class="field">
      <%= form.label :categoy_id, 'Categoria' %>
      <%= form.select :category_id, options_for_select(Category.all.map { |category| [category.name, category.id] }) %>
    </div>

    <div class="field">
      <%= form.label :quantity, 'Estoque' %>
      <%= form.number_field :quantity, value: @product.quantity %>
    </div>


    <div class="field">
      <%= form.label :price, 'Preço' %>
      <%= form.number_field :price, step: :any, value: @product.price %>
    </div>

    <br>
    <div class="actions">
      <%= form.submit "Atualizar produto" %>
    </div>

    <% end %>

<% end %>

app/views/products/index.html.erb
<% if logged_in? %>
  <% if current_user.adm == true %>
    <h1>Nossos produtos</h1>

    <table class="text-center">
      <thead>
      <tr>
        <th>Nome</th>
        <th>Marca</th>
        <th>Volume</th>
        <th>Categoria</th>
        <th>Preço</th>
        <th colspan="5"></th>
      </tr>
      </thead>

      <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.brand %></td>
          <td><%= product.volume %></td>
          <td><%= product.category.name %></td>
          <td>R$<%= '%.2f' % product.price %></td>
          <td><%= link_to 'Detalhes', product_path(product) %></td>

          <% unless current_user.nil? %>
            <% unless current_user.adm != true %>
              <td><%= link_to 'Editar', edit_product_path(product) %></td>
              <td><%= link_to 'Deletar', product_path(product), method: :delete, data: {confirm: 'Deletar produto?'} %></td>
            <% end %>
          <% end %>

        </tr>
      <% end %>
      </tbody>
    </table>
    <br>

    <% unless current_user.nil? %>
      <% unless current_user.adm != true %>
        <%= link_to 'Novo Produto', new_product_path %>
      <% end %>
    <% end %>
    <%= link_to 'Meu Carrinho', orders_path %>

  <% end %>
<% else %>
  <h3> Acesso negado, pagina somente para administradores</h3>
<% end %>

app/views/products/new.html.erb
<% if current_user.nil? %>
  <h4 style="color: red">Erro: é preciso estar logado em uma conta com função de administrador para acessar essa página!</h4>

<% elsif current_user.adm != true %>
  <h4 style="color: red">Erro: é preciso ter permissão de administrador para acessar essa página!</h4>

<% else %>
  <h1>Novo Produto</h1>

  <%= form_with model: @product do |form| %>
    <div class="field">
      <%= form.label :name, 'Nome' %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :brand, 'Marca' %>
      <%= form.text_field :brand %>
    </div>

    <div class="field">
      <%= form.label :volume, 'Volume' %>
      <%= form.text_field :volume %>
    </div>

  <div class="field">
    <%= form.label :alcoholic, 'Alcoólico?' %>
    <%= form.select :alcoholic, [['Sim', true], ['Não', false]] %>
  </div>

  <div class="field">
    <%= form.label :category_id, 'Categoria' %>
    <%= form.select :category_id, options_for_select(Category.all.map { |category| [category.name, category.id] }) %>
  </div>

  <div class="field">
    <%= form.label :quantity, 'Estoque' %>
    <%= form.number_field :quantity, min: 0 %>
  </div>


  <div class="field">
    <%= form.label :price, 'Preço' %>
    <%= form.number_field :price, step: :any, min: 0%>
  </div>

  <br>
  <div class="actions">
    <%= form.submit "Criar produto" %>
  </div>
  <% end %>

<% end %>

app/views/products/show.html.erb
<h1>Detalhes do produto</h1>

<p>
  <strong>Nome:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @product.volume %>
</p>

<p>
  <strong>Alcoólico:</strong>
  <%= @product.alcoholic %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @product.category.name %>
</p>

<p>
  <strong>Quantidade em estoque:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Preço:</strong>
  R$<%= '%.2f' %  @product.price %>
</p>

<% if current_user.nil? %>
  <h5>Logue em sua conta para comprar o produto <%= link_to 'Logar', log_in_path %></h5>

<% elsif in_cart?(@product) %>
  <h4>Produto já consta em seu carrinho.<%= link_to 'Ver', orders_path %></h4>

<% elsif @product.quantity > 0 %>
  <h4>Comprar</h4>
  <%= form_with model: @order do |form| %>
    <div class="field">
      <%= form.label :quantity, 'Quantidade:' %>
      <%= form.select :quantity, options_for_select(1..@product.quantity) %>
    </div>

    <div class="field">
      <%= form.label :user_id, 'Usuário:'%>
      <%= form.select :user_id, [[current_user.name, current_user.id]] %>
    </div>

    <div class="field">
      <%= form.label :product_id, 'Produto:'%>
      <%= form.select :product_id, [[@product.name, @product.id]] %>
    </div>

    <div class="actions">
      <%= form.submit "Adicionar ao carrinho" %>
    </div>

  <% end %>

  <% else %>
  <h4>Oops! Parece que o estoque desse produto esgotou :(</h4>
<% end %>
<p>
  <%= link_to 'Voltar', products_path %>
</p>